### ISSUE TITLE
Skill Issue

### ISSUE THREAD

**Issue by DISREL** [LaCrak27/reexerted-clops#1]
fucking lol

**Comment by LaCrak27** [comment]
lmao

**Comment by LaCrak27** [comment]
this is staying for the memories

**Comment by DISREL** [comment]
Lacrackussy didn't understand the joke feelsbadman

**Comment by LaCrak27** [comment]
if my future employer ever looks at this, please forgive me lmao

**Comment by JuergenFuchs** [comment]
In case of an investigation by any federal entity or similar, I do not have any involvement with this group or with the people in it, I do not know how I am here, probably added by a third party, I do not support any actions by the members of this group. Everything I have posted here is purely satire and will be treated as such in a court of law. I have committed no crimes and am an innocent bystander.
